### ISSUE TITLE
Bases de Datos

### ISSUE THREAD

**Issue by delucas** [PrograAvanzada2016/jrpg#3]
Aún no habría que agregar la base de datos. No porque no querramos que anticipen trabajo, sino porque es más fácil hacerla cuando se comprende qué cosa realmente debe guardarse, y qué no.
La mayoría de las cosas que guardan no son necesarias.

**Comment by hymuura** [comment]
ya lo charlamos con el equipo, teníamos esa duda en un principio pero bueno queríamos estimar algo, pero si vamos a tomar su consejo muchas gracias profesores :)
