### ISSUE TITLE
Castas

### ISSUE THREAD

**Issue by delucas** [PrograAvanzada2016/jrpg#5]
No utilicen un switch para algo que puede resolverse con polimorfismo

https://github.com/PrograAvanzada2016/jrpg/blob/master/cliente/AnotherWorld/src/prograavanzada2016/anotherworld/castas/Curandero.java#L17

**Comment by delucas** [comment]
Por ejemplo, en `Curandero`:

``` java
        public void calcularStats(Personaje p) {
            calcularStats(p.getRaza());
        }
```

**Comment by hymuura** [comment]
listo corregido, gracias por la observación
