### ISSUE TITLE
Sobre carpetas espurias

### ISSUE THREAD

**Issue by delucas** [PrograAvanzada2016/jrpg#8]
Los directorios `.recommenders` y `RemoteSystemsTempFiles` no deberian estar presentes en ningún proyecto.
Deben [eliminarlas del repo](http://stackoverflow.com/questions/1143796/remove-a-file-from-a-git-repository-without-deleting-it-from-the-local-filesyste), y agregarlas al archivo `.gitignore` para que no vuelvan a aparecer

**Comment by hymuura** [comment]
se eliminaron las carpetas espurias y se actualizo el .gitIgnore :)
