### ISSUE TITLE
Sobre las entregas en formato binario

### ISSUE THREAD

**Issue by delucas** [PrograAvanzada2016/jrpg#9]
Se pidió que las entregas no estén en formatos binarios (.docx, en este caso).
Cambiar el archivo para que sea formato markdown, y eliminar el .docx

**Comment by hymuura** [comment]
profesores como están? dos consultas con respecto a este issue:

1) Quizás nosotros estemos en el error que es lo mas probable pero el día que dijeron de hacer esta entrega recuerdo haber preguntado el formato y nos dijeron que en cualquier formato, en un word, en un .md que era lo mismo. Ya igual lo actualizamos como nos lo piden pero mi pregunta es tuvimos una entrega negativa por eso?

2) Con respecto al documento vamos a recibir algún tipo de corrección? porque tenemos dudas de cual seria la forma correcta de enviar los comandos desde el cliente al servidor, con lo que pusimos estamos algo encaminados?

Muchas gracias Saludos!
Another World

**Comment by delucas** [comment]
¡Hola!
1. No es negativo por eso, no te preocupes.
2. Lo vamos a ver en vivo. La idea de la entrega era que se encuentren con el problema antes de tenerlo :) El sábado discutimos al respecto.

**Comment by hymuura** [comment]
muchas gracias :+1: 

Saludos!
